### ISSUE TITLE
Problem with SDK

### ISSUE THREAD

**Issue by ALEHACKsp** [ethanedits/Warzone-Project#10]
![image](https://user-images.githubusercontent.com/45023050/171495176-bb336e5c-2885-4fea-b1a3-5ba0f0f76703.png)

**Comment by ethanedits** [comment]
Update the draven.txt file and press enter

**Comment by ethanedits** [comment]
it wil dump decryption.cpp and Offsets.h into the WarzoneSDK-Dump folder

**Comment by ethanedits** [comment]
This is from a while ago, and draven isnt even releasing his offset dumps anymore so the dumper python script is probably outdated.
