### ISSUE TITLE
PID / Driver building

### ISSUE THREAD

**Issue by xyinvsk** [ethanedits/Warzone-Project#2]
Could not find PID
- Class "Sample" is reserved by Microsoft.

I updated offsets etc, but i cant "build" the driver part - and if i run the client.exe it fails to find PID. ?

**Comment by ShymonYT** [comment]
Did you solve this?

**Comment by xyinvsk** [comment]
Not yet - havent looked into it more.
- I posted updated offsets and decryption files and has been away since.

Look at my Fork

**Comment by rexmdz** [comment]
delete the inf file and turn off infcat in settings of the project.

**Comment by ShymonYT** [comment]
@rexmdz So when i build the drivers from the modern_warfare_driver folder should i delete the inf file? And how to turn off infcat? Pls help me

**Comment by ShymonYT** [comment]
@rexmdz  So i found inf2cat in Warzone-Project/WarzoneProject/modern_warfare_driver/modern_warfare_driver.vcxproj
So should I delete the inf file from folder modern_warfare_driver and then turn this: <Inf2CatUseLocalTime>true</Inf2CatUseLocalTime> off?

**Comment by ShymonYT** [comment]
@xyinvsk so i ran the cheat. You need to download another kdmapper bc this didnt work for me and you need to compile it. Place it in the x64/relase folder and load the drivers that are already built and you are good. No more could not find PID error

**Comment by ethanedits** [comment]
feel free to link the kdmapper that worked for you and i will update the repo

**Comment by ShymonYT** [comment]
https://github.com/TheCruZ/kdmapper this worked for me. Do you know what should i do when i have radeon gpu and no Nvidia overlay?

**Comment by xyinvsk** [comment]
Nothing working here yet.
- Gonna play around with it for abit.

**Comment by xyinvsk** [comment]
@ShymonYT 
- A way we can get into a DM Convo?

**Comment by DMHoodz** [comment]
could use some help discord Hoodz#1847

**Comment by DMHoodz** [comment]
@ShymonYT you got it to build

**Comment by ShymonYT** [comment]
@xyinvsk write there your discord

**Comment by ShymonYT** [comment]
@DMHoodz you dont need to build the drivers. Use this kdmapper https://github.com/TheCruZ/kdmapper (complie it, then put it to the \Warzone-Project-main\Warzone-Project-main\WarzoneProject\x64\Release and run the existing driver (modern_warfare_driver.sys) with the kdmapper and you should be good. Also you can try the existing kdmapper but it didnt work for me.

**Comment by DMHoodz** [comment]
can i get you in a call by chance?

**Comment by DMHoodz** [comment]
@ShymonYT def be easy if we was in a call

**Comment by xyinvsk** [comment]
I will update the repo ASAP.
I got it all functioning from 1 executeable.

- Although i dont have Nvidia, so i will be trying to add some other hijacking to render.

**Comment by ShymonYT** [comment]
@xyinvsk thanks it would be great. I will wait

**Comment by DMHoodz** [comment]
what are the updated offsets/decrypt files

**Comment by xyinvsk** [comment]
@DMHoodz 
I uploaded the new offsets/decryption data from latest game dump - repo was 3-4 months old.
