### ISSUE TITLE
Latest Offsets

### ISSUE THREAD

**Issue by 1tsMeMario** [ethanedits/Warzone-Project#5]
Dravens offsets on unknowncheats are relatively old. and im a bot so i can't make since of what has been posted recently to try and update it so any help would be appreciated.

**Comment by xyinvsk** [comment]
Grab the latest, replace and run the .py file to generate a new set - move those into the project.

Ill update it tomorrow.

**Comment by 1tsMeMario** [comment]
ive looked through unknowcheats and replaced them with offsets listed as
latest and the src wont compile. it just lists a bunch of errors

**Comment by jiguja** [comment]
I've already updated the offsets, but it still says : you're either not in game or cheat is outdated..

**Comment by OMW2** [comment]
Very new to this, but does someone who knows what they're doing want to walk through some of the code in this to help me get a better understanding of it so I can fix some errors that keep showing up that put me in debug mode instead of letting me attach to the game?

**Comment by OMW2** [comment]
![Errors](https://user-images.githubusercontent.com/99453576/153965183-bbe023c1-e28f-4065-9d2a-287919faa56b.PNG)
Here are the errors I currently am getting.

**Comment by 1tsMeMario** [comment]
well for one you need Visual Studio 2019 to use Windows Kernel Driver Build
Tools

https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
download and install Visual Studio 2019
then download and install Windows 11 SDK

once thats done install the WDK for Windows 11 after thats complete it
should automatically prompt you to install the wdk extension for Visual
Studio 2019. go ahead and install that.


this tutorial will fix the last error you saw as well as provide the proper
build environment for the project solution.


as far as the other errors you need to understand the language more to fix
the code.

**Comment by OMW2** [comment]
I have Visual Studio 19 but I am still on Windows 10. Do I need Windows 11 to use this? Thanks for the link I will try to do more research to fix the other part of the code I am having trouble with.

**Comment by 1tsMeMario** [comment]
no u need the wdk and sdk to build kernel mode drivers.

**Comment by OMW2** [comment]
Ok, Doing that fixed the Kenral driver issue. Do you have any insight as to where to look to fix the "Element <LanguageStandard> has an invalid value of "stdcpp20" and "MSB6011 Invalid parameters passes to the Microsoft.Build.CPPYasks.Cl task."? As for the 'auto' is not allowed here I may be using an incorrect version of C++ it seems like. I am still trying to dig for that answer online. I appreciate the guidance!

**Comment by 1tsMeMario** [comment]
no idea sorry. i dont know C++ that good really

**Comment by OMW2** [comment]
Does your version have this line of code in sdk.h?    bool inRange(auto low, auto high, auto x)
it is line 92 on mine.

**Comment by OMW2** [comment]
Or can I see how you properties settings are setup? Project>Properties>C/C++>Language

**Comment by 1tsMeMario** [comment]
i dont have the project anymore dude.

**Comment by headlessNode** [comment]
hey you solve the stdcpp 20 issue by changing the language standard in project properties
