### ISSUE TITLE
Updating the cheat 

### ISSUE THREAD

**Issue by BCKILLER** [ethanedits/Warzone-Project#8]
Im really confused i dont know what .txt file hes talking about can someone help

**Comment by BCKILLER** [comment]
Ok ihave the offsets pasted into the draven ,txt but when i run the python script it doesnt work

**Comment by ethanedits** [comment]
The python script is just parsing the offsets file and draven might have changed the format of that, so the script would be outdated now perhaps. Try manually updating offsets.
